# CMI 曾经的汉化发布地址（无法访问）：https://www.mcbbs.net/thread-791419-1-1.html
# 汉化 by 原MCBBS PCD小组 秋风残叶
# 催更汉化请加群 476731621 （敬祝lona先生早日找到工作）
# CMI自带的Locale_ZH.yml为台式繁体汉化包，不建议中国大陆服主使用，中国人不骗中国人

# 语言文件
Language: CN
# 从Github自动下载语言文件
# 鉴于国内网络情况，不建议开启
LanguageDownload: false
# 自动更新
AutoUpdate: false
ExploitPatcher:
  Placeholders:
    blocked:
      # 默认情况下PlaceholderAPI变量 %checkitem_...% 是禁用的（以避免bug）
      # 除非你有把握，否认不应该关上这一项
      checkItem: true
Skins:
  # 从mojang服务器在线更新皮肤数据的时间间隔，单位是分钟
  # 请注意，最小的间隔必须是1分钟及以上，最好妥善设置，比如几个小时
  # 玩家看到皮肤有改变，需要该玩家重新登陆服务器或者手动执行换肤指令
  SkinUpdateTimer: 1320
  # 即将更新皮肤数据时，每隔多少分钟朝mojang服务器发送一次数据？
  # 这个设置可以避免大量数据请求堵塞网络
  SkinRequestFrequency: 10
GlobalGui:
  # 在Zrips所有系列插件（例如CMI、Residence）菜单GUI中，用来填充空白格子的物品
  EmptyField: BLACK_STAINED_GLASS_PANE
  Pages:
    # 所有GUI菜单中“上一页”按钮的材质
    Previous: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzdhZWU5YTc1YmYwZGY3ODk3MTgzMDE1Y2NhMGIyYTdkNzU1YzYzMzg4ZmYwMTc1MmQ1ZjQ0MTlmYzY0NSJ9fX0=
    # 所有GUI菜单中“下一页”按钮的材质
    Next: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjgyYWQxYjljYjRkZDIxMjU5YzBkNzVhYTMxNWZmMzg5YzNjZWY3NTJiZTM5NDkzMzgxNjRiYWM4NGE5NmUifX19
    # 所有GUI菜单中“信息”按钮的材质
    Middle: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmEyYWZhN2JiMDYzYWMxZmYzYmJlMDhkMmM1NThhN2RmMmUyYmFjZGYxNWRhYzJhNjQ2NjJkYzQwZjhmZGJhZCJ9fX0=
  # 关闭按钮的材质
  Close: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzM4YWIxNDU3NDdiNGJkMDljZTAzNTQzNTQ5NDhjZTY5ZmY2ZjQxZDllMDk4YzY4NDhiODBlMTg3ZTkxOSJ9fX0=
  # 信息按钮的材质
  Info: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjcwNWZkOTRhMGM0MzE5MjdmYjRlNjM5YjBmY2ZiNDk3MTdlNDEyMjg1YTAyYjQzOWUwMTEyZGEyMmIyZTJlYyJ9fX0=
Spawners:
  # 当使用 spawner:random 变量时，可选择的刷怪笼种类列表
  mysterySpawners:
  - skeleton
  - zombie
  - silverfish
  - panda
  - fox
RMCCommands:
  # 若开启此项，我们将在可能的情况下包含一个命令，以指示在使用 RMC 命令时执行的命令（此处搬运者没有读懂）
  ConsoleLog: true
Images:
  # 用做图片占位的符号
  # 不支持颜色代码
  # 服务器重启之后此占位符将会发挥机能
  Filler: ⬛
  # 若图片为空，用作占位的符号
  # 此处是支持颜色代码的
  EmptyFiller: '&7_|'
Colors:
  # 启用此项，插件将尝试识别简化Hex颜色代码，比如 #f6f6f6 或者 #ff6 （在原本识别 {#f6f6f6} 或者 {#red} 的基础上）
  # 请注意，简化Hex颜色代码不支持渐变色，也不支持自己命名的颜色
  OfficialHex: true
  # 启用此项，插件将尝试识别特殊Hex颜色代码，比如 &#f6f6f6 或者 &#ff6 （在原本识别 {#f6f6f6} 或者 {#red} 的基础上）
  # 请注意，特殊Hex颜色代码不支持渐变色，也不支持自己命名的颜色
  QuirkyHex: true